name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

# NOTE: by using $GITHUB_REF_NAME this will only work as the main action, not one invoked by others.
jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          ls -lah --color=always
          pwd -P
          echo '=================='
          make clean build
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              artificial-clippy.zip

